### ISSUE TITLE
Choose sidebar or create it maybe used in posts ,...

### ISSUE THREAD

**Issue by sergiubagrin** [ThemeFuse/Unyson-Sidebars-Extension#1]
"Choose sidebar or create" it maybe used in posts , pages and categories.
It will be great if supported :)

**Comment by sergiubagrin** [comment]
Q: "Choose sidebar or create" it maybe used in posts , pages and categories.
It will be great if supported :)

A: From my point of view it is not necessary to add this option on pages, posts, categories. I dont like when on Add New Page i have a lot of unnecessary option in our case Sidebar position. From my point of view all actions with sidebars must be in one place like it is right know under widgets menu.

**Comment by danyj** [comment]
@sergiubagrin  Sorry to disagree with you on this one. 
You already have a page builder that transforms everything on a given page. The user should not go an extra step to widgets in order to add/pick a sidebar for the page he/she is building.

**Comment by sergiubagrin** [comment]
@danyj - i understand what you mean. 

I will try to explain for different types of pages:

All sites/pages in the internet include 2 types of pages: structured and unstructured

Structured Pages (with a specific template): 
1. Blog/ News
2. Portfolio
3. Products
4. Events
5. Learning 
6. ...

Unstructured (to create this kind of pages it is needed a page builder or shortcodes)
1. Homepages
2. About
3. Contact
4. ...

Situation:
1. I want to add first Blog Post to my site. Step 1: I open Blog Posts -> Add New Post page. Step 2: I  add content and press Save button. Step 3: I want to add a sidebar. At this point i don't have a sidebar so i need to go to Appearance -> Widgets and create a new Sidebar with my widgets for blog posts and i will specify that this sidebar will be available for all Blog Posts like you can see in this screen: http://screencast.com/t/q7o8uoPKq Step 4: I want to add a second Blog Post to my site. Question 1: Why i need an option for sidebar? Second blog post will include the same sidebar added for the first blog post: http://screencast.com/t/q7o8uoPKq Question 2: How much blog post sidebars i want to have in a site? Each time you want to add a new sidebar it is needed to go to Appearance -> Widgets. The same with events, projects, products, ...
2. I want to add first Page to my site (about, contact, home). Step 1: I open Pages -> Add New Page. Step 2: I  add content and press Save button. Step 3: I want to add a sidebar. At this stage i have only 1 sidebar "Blog Posts sidebar". I can't use blog sidebar for my (About Us, Contact Us, ...) page so a page option is not useful. If i want to add a specific sidebar for contact page it is needed to go to Appearance -> Widgets and create it add specific widgets like contact data or about data: http://screencast.com/t/HRGuUMJ6GJm

If i want to add a sidebar for all pages on my site i can use: http://screencast.com/t/8Y9Ug3p40
If i want to add a specific sidebar to specific pages first of all i need to create it and after this to assign it to specific or grouped pages. 

Every time i add a new event, project, blog, product, page, ... default sidebar will be assigned to this page: http://screencast.com/t/PgvimEWJZtZ In case i want a specific sidebar for a new page first of all i need to create this sidebar in Appearance -> Widgets 

---

Also i want Add New Post/ Page pages to be clean the same as wordpress default pages. From my point of view people add a lot of options in each page, post. 

---

And my final question is how much sidebars do you need for your sidebar? for your events? for your products? 

Do you need the same sidebar for About and Contact or Services pages? 

I analysed a lot of site created by end user at themefuse and users need 2-4 sidebars. 1. Homepage 2. Blog 3. Contact form. 

A small number of users want 2 different sidebars for blog posts or events. Also users want a sidebar for all pages from site which can be created with: http://screencast.com/t/tjHk9wAweo and 2-3 sidebars for specific pages for example: Contact, Blog Posts, About which can be created with: http://screencast.com/t/eIxNB8mwe

**Comment by danyj** [comment]
@sergiubagrin I understand your point of view 110%,  but looks like you are not considering mine. 
who are we to tell users how many sidebras should be there?
you and me are here to compete with others who already have the sidebars on cats/posts/pages
and make our customers use unyson.

think of this, you page builder resembles enfold 99.99% also very close to avada, 
both of those have the sidebars on those edits. if we are to compete and get their users to use
unyson, than we need those little tweaks that each of them already has. 

I am not saying that you should move those from widgets, just give devs an option to add those
to cats/posts/pages edit views.

**Comment by sergiubagrin** [comment]
@danyj 

I added it to do list: https://trello.com/c/kqsnU2Nh/56-change-sidebar-from-page-post

**Comment by danyj** [comment]
Thank you!

**Comment by ghost** [comment]
[Here](https://github.com/ThemeFuse/Unyson-Extensions-Approval/issues/43) is described how to enable this feature.
