### ISSUE TITLE
Sidebar metabox empty when add/edit post/portfolio

### ISSUE THREAD

**Issue by dinhtungdu** [ThemeFuse/Unyson-Sidebars-Extension#10]
Sidebar metabox works great with page, but not for other post types. Sidebar metabox doesn't show image for sidebar position ([screenshot](http://prnt.sc/bw7m08))

It works well with `page`.

**Comment by ghost** [comment]
https://github.com/ThemeFuse/Unyson-Sidebars-Extension/issues/12#issuecomment-236876714

**Comment by ghost** [comment]
https://github.com/ThemeFuse/Unyson-Sidebars-Extension/issues/12#issuecomment-238259120
