### ISSUE TITLE
Auto set no-sidebar option when showing sidebar meta box in post type.

### ISSUE THREAD

**Issue by dinhtungdu** [ThemeFuse/Unyson-Sidebars-Extension#12]
When I show metabox in post type ( here is `page`, because only page worked ), Unyson auto set no sidebar option in metabox.

I think we shouldn't auto set sidebar without user's choice,  we can add an options like `Default` to keep default appearance for page. Then if user choose other layout, we can set option at this point.

An other issue with current approach is a bit hard to maintain. The number of sidebar created will be equal to number of page. For example in my themes, almost page will be no sidebar, so I think it's better to choose no sidebar for Page post type, then we can set specific option for page that have different layout.

Ps: If this is not clear enough, ask me for screenshot.

**Comment by ghost** [comment]
The code responsible for sidebar picker is
- https://github.com/ThemeFuse/Unyson-Sidebars-Extension/blob/997b38170c41494c2b4e457e564418293a5dd35d/class-fw-extension-sidebars.php#L91
- https://github.com/ThemeFuse/Unyson-Sidebars-Extension/tree/997b38170c41494c2b4e457e564418293a5dd35d/includes/option-type/sidebar-picker

Can you fix this and provide a pull request?

**Comment by dinhtungdu** [comment]
Yes, I'll try tomorrow. Too busy right now.

**Comment by dinhtungdu** [comment]
Fixed. #13
