### ISSUE TITLE
filter in docs

### ISSUE THREAD

**Issue by andronic90** [ThemeFuse/Unyson-Sidebars-Extension#15]
Problem in docs sidebars filters: https://static.md/575899d2db3af3aa0033ce4142e98909.png, this are functional filters: "fw_ext_sidebars_post_types" and "fw_ext_sidebars_taxonomies".

Thank you!

**Comment by ViorelEremia** [comment]
https://github.com/ThemeFuse/Unyson-Documentation/commit/5b6bfd3079fe3b3fbd0d330bb39c0ed52a7ed708
