### ISSUE TITLE
Custom sidebar not showing up in custom template

### ISSUE THREAD

**Issue by erralb** [ThemeFuse/Unyson-Sidebars-Extension#4]
Hi,

In a page template I created, where I am using the `<?php get_sidebar(); ?>` function, the custom sidebar I am creating in the back-office is not showing up... 
Any idea why?

**Comment by llemurya** [comment]
@ierpe If you registered a custom sidebar.

``` php
add_action( 'widgets_init', 'theme_slug_widgets_init' );
function theme_slug_widgets_init() {
    register_sidebar( array(
        'name' => __( 'Main Sidebar', 'theme-slug' ),
        'id' => 'sidebar-1',
        'description' => __( 'Widgets in this area will be shown on all posts and pages.', 'theme-slug' ),
        'before_widget' => '<li id="%1$s" class="widget %2$s">',
    'after_widget'  => '</li>',
    'before_title'  => '<h2 class="widgettitle">',
    'after_title'   => '</h2>',
    ) );
}
```

You must show it with `dynamic_sidebar()` function.

``` php
dynamic_sidebar( 'sidebar-1' );
```

`get_sidebar()` function is used to load a custom sidebar template from your theme. Please say If it helps. If not , give us more details about the problem. Thanks!

**Comment by erralb** [comment]
I did not register a custom sidebar, I created one in the backoffice with the unyson sidebar extension, and it's not showing up in my template...

**Comment by erralb** [comment]
I mean, what I want is to use the sidebar plugin, not having to declare sidebars in my theme, otherwise what's the point of using the sidebar extension ?

**Comment by llemurya** [comment]
@ierpe please make an video screencast how to reproduce your bug to answer more detailed at your question.Thanks.

**Comment by erralb** [comment]
![sidebar](https://cloud.githubusercontent.com/assets/790992/8591806/050be04a-262b-11e5-9ad3-1091396340af.png)

I created a sidebar with the Unyson sidebar extension.
But it is not replacing the default sidebar.

In my page template php file, the `<?php get_sidebar(); ?>` php function is used, but it always shows the default sidebar and not the sidebar I created and assigned to the page.

Is it not clear? I don't know how to explain it better

**Comment by llemurya** [comment]
@ierpe you created an sidebar only for a specific page name Page-Le fil LSD, it will replaced only on this page.If you want for all pages ,create a sidebar for grouped pages.Please make a try and give us an answer.Thanks!

**Comment by erralb** [comment]
Yes, I did, and on this specific page, the default sidebar is not being replaced by the one I created

**Comment by llemurya** [comment]
@ierpe please watch [this video tutorial](https://youtu.be/T3147Pr-vX8) and say if it helps you.I am waiting for your response.

**Comment by erralb** [comment]
I know how to use the extension, I used it before and it worked fine, but not with a child theme.
Is it working for you in a child theme with a custom page template ???

I don't understand what you don't understant in my problem....

**Comment by llemurya** [comment]
@ierpe please watch [this video](https://youtu.be/MoBbOftjYFg). It is an example with child theme. I am waiting for a response.

**Comment by llemurya** [comment]
@ierpe please answer in order to resolve this issue.

**Comment by erralb** [comment]
Hi, I didn't have time yet to test everything, but so far this issue is not resolved for me

**Comment by llemurya** [comment]
@ierpe you watched the last video in the comment that I have posted 4 days ago?

**Comment by erralb** [comment]
yes I watched it but I haven't had the time to test it yet, I will test it during the week and let you know!
